---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cninfra.ibanmarco.io
  resources:
  - snstosqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cninfra.ibanmarco.io
  resources:
  - snstosqs/finalizers
  verbs:
  - update
- apiGroups:
  - cninfra.ibanmarco.io
  resources:
  - snstosqs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - update
